In [1]:
import numpy as np

## 1

In [4]:
r = np.array([3, 2])
A = np.array([
    [1/2, -1],
    [0, 3/4]
])

A.dot(r)

array([-0.5,  1.5])

## 2

In [5]:
s = np.array([-2, 4])
A = np.array([
    [1/2, -1],
    [0, 3/4]
])

A.dot(s)

array([-5.,  3.])

## 3

In [7]:
M = np.array([
    [-1/2, 1/2],
    [1/2, 1/2]
])

In [8]:
M.dot(np.array([1, 0]))

array([-0.5,  0.5])

In [9]:
M.dot(np.array([0, 1]))

array([0.5, 0.5])

## 4

In [16]:
matrices = [
    [
        [np.sqrt(3/2), np.sqrt(3/2)],
        [1/2, 1/2]
    ],
    [
        [-1/2, 0],
        [0, np.sqrt(3/2)]
    ],
    [
        [np.sqrt(3/2), -1/2],
        [1/2, np.sqrt(3/2)]
    ],
    [
        [1/2, 0],
        [-np.sqrt(3/2), 1/2]
    ],
]

In [17]:
for m in matrices:
    print(np.array(m).dot(np.array([1, 0])))

[1.22474487 0.5       ]
[-0.5  0. ]
[1.22474487 0.5       ]
[ 0.5        -1.22474487]


In [18]:
for m in matrices:
    print(np.array(m).dot(np.array([0, 1])))

[1.22474487 0.5       ]
[0.         1.22474487]
[-0.5         1.22474487]
[0.  0.5]


## 5

In [22]:
M1 = np.array([
    [1, 0],
    [0, 8]
])
M2 = np.array([
    [1, 0],
    [-1/2, 1]
])

M1.dot(M2)

array([[ 1.,  0.],
       [-4.,  8.]])