In [45]:
import numpy as np

## 2

In [17]:
old_two = np.array([3, 4, 1])

In [19]:
old_one = np.array([1, 3/2, 1/2])

In [20]:
np.divide(old_two, 4 - old_one)

array([1.        , 1.6       , 0.28571429])

In [32]:
new_two = (old_two - 3*old_one) * -2
new_two

array([-0.,  1.,  1.])

## 3

In [73]:
old_three = np.array([2, 8, 13])

In [85]:
old_three - 4*(old_one)

array([-2.,  2., 11.])

In [86]:
2-(2*9/4)

-2.5

In [79]:
-(1/4) - 5*(-1/2)

2.25

In [80]:
(9/4)*(1/7)

0.3214285714285714

## 7

In [66]:
A = np.array([
    [1, 1, 1],
    [3, 2, 1],
    [2, 1, 2],
])

np.linalg.inv(A)

array([[-1.50000000e+00,  5.00000000e-01,  5.00000000e-01],
       [ 2.00000000e+00,  5.55111512e-17, -1.00000000e+00],
       [ 5.00000000e-01, -5.00000000e-01,  5.00000000e-01]])

In [67]:
A.dot(np.linalg.inv(A))

array([[ 1.00000000e+00,  5.55111512e-17,  0.00000000e+00],
       [-1.66533454e-16,  1.00000000e+00,  0.00000000e+00],
       [-3.33066907e-16,  1.11022302e-16,  1.00000000e+00]])

In [62]:
A_inv = np.array([
    [-1, 0, 1],
    [1, 1, -2],
    [1, -1, 1],
])
A.dot(A_inv)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 8

In [64]:
import numpy as np

A = [[1, 1, 3],
     [1, 2, 4],
     [1, 1, 2]]
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  2.],
       [-2.,  1.,  1.],
       [ 1., -0., -1.]])

In [ ]:
import numpy as np
A = [[4, 6, 2],
     [3, 4, 1],
     [2, 8, 13]]

s = [s1, s2, s3]

r = np.linalg.solve(A, s)