In [25]:
import numpy as np
from fractions import Fraction

In [33]:
def change_basis(v, b1, b2):
    v_b1 = (v*b1).sum() / (b1*b1).sum()
    v_b2 = (v*b2).sum() / (b2*b2).sum()
    v_b1 = v_b1 if v_b1.is_integer() else Fraction(str(v_b1))
    v_b2 = v_b2 if v_b2.is_integer() else Fraction(str(v_b2))
    return np.array([v_b1, v_b2])

In [48]:
def change_basis(v, bn):
    vn = []
    for b in bn:
        v_b = (v*b).sum() / (b*b).sum()
        #v_b = v_b if v_b.is_integer() else Fraction(str(v_b))
        vn.append(v_b)
    return np.array(vn)

## 1

In [34]:
v = np.array([5, -1])
b1 = np.array([1, 1])
b2 = np.array([1, -1])

In [35]:
(v*b1).sum() / (b1*b1).sum()

2.0

In [36]:
(v*b2).sum() / (b2*b2).sum()

3.0

In [37]:
change_basis(v, b1, b2)

array([2., 3.])

Answer is $v_b = \begin{bmatrix}2\\3\end{bmatrix}$.

## 2

In [39]:
v = np.array([10, -5])
b1 = np.array([3, 4])
b2 = np.array([4, -3])

In [40]:
change_basis(v, b1, b2)

array([Fraction(2, 5), Fraction(11, 5)], dtype=object)

Answer is $v_b = \begin{bmatrix}2/5\\11/5\end{bmatrix}$.

## 3

In [41]:
v = np.array([2, 2])
b1 = np.array([-3, 1])
b2 = np.array([1, 3])

In [42]:
change_basis(v, b1, b2)

array([Fraction(-2, 5), Fraction(4, 5)], dtype=object)

## 4

In [43]:
v = np.array([1, 1, 1])
b1 = np.array([2, 1, 0])
b2 = np.array([1, -2, -1])
b3 = np.array([-1, 2, -5])

In [49]:
change_basis(v, [b1, b2, b3])

array([ 0.6       , -0.33333333, -0.13333333])

Answer is $v_b = \begin{bmatrix}3/5\\-1/3\\-2/15\end{bmatrix}$

## 5

In [50]:
v = np.array([1, 1, 2, 3])
b1 = np.array([1, 0, 0, 0])
b2 = np.array([0, 2, -1, 0])
b3 = np.array([0, 1, 2, 0])
b4 = np.array([0, 0, 0, 3])

In [51]:
change_basis(v, [b1, b2, b3, b4])

array([1., 0., 1., 1.])