In [15]:
from sympy import *

import numpy as np
np.set_printoptions(suppress=True)

In [9]:
l, a, b, c, d = symbols('l, a, b, c, d')

f = l**2 - (a + d)*l + (a*d - b*c)
f

a*d - b*c + l**2 - l*(a + d)

## 1

In [11]:
T = np.array([
    [6, -1],
    [2, 3]
])
C = np.array([
    [1, 1],
    [1, 2]
])
C_inv = np.linalg.inv(C)
C_inv

array([[ 2., -1.],
       [-1.,  1.]])

In [12]:
C_inv @ T @ C

array([[5., 0.],
       [0., 4.]])

## 2

In [16]:
T = np.array([
    [2, 7],
    [0, -1]
])
C = np.array([
    [7, 1],
    [-3, 0]
])
C_inv = np.linalg.inv(C)
C_inv

array([[ 0.        , -0.33333333],
       [ 1.        ,  2.33333333]])

In [17]:
C_inv @ T @ C

array([[-1.,  0.],
       [ 0.,  2.]])

## 3

In [20]:
T = np.array([
    [1, 0],
    [2, -1]
])
C = np.array([
    [1, 0],
    [1, 1]
])
C_inv = np.linalg.inv(C)
C_inv

array([[ 1.,  0.],
       [-1.,  1.]])

In [21]:
C_inv @ T @ C

array([[ 1.,  0.],
       [ 0., -1.]])

## 4

In [22]:
a = symbols('a')

D = np.array([
    [a, 0],
    [0, a]
])
C = np.array([
    [1, 2],
    [0, 1]
])
C_inv = np.linalg.inv(C)
C_inv

array([[ 1., -2.],
       [ 0.,  1.]])

In [23]:
C @ D @ C_inv

array([[1.0*a, 0],
       [0, 1.0*a]], dtype=object)

## 5

In [29]:
n = 3
D = np.array([
    [5**n, 0],
    [0, 4**n]
])
C = np.array([
    [1, 1],
    [1, 2]
])
C_inv = np.linalg.inv(C)
C_inv

array([[ 2., -1.],
       [-1.,  1.]])

In [30]:
C @ D @ C_inv

array([[186., -61.],
       [122.,   3.]])

## 6

In [31]:
n = 3
D = np.array([
    [(-1)**n, 0],
    [0, 2**n]
])
C = np.array([
    [7, 1],
    [-3, 0]
])
C_inv = np.linalg.inv(C)
C_inv

array([[ 0.        , -0.33333333],
       [ 1.        ,  2.33333333]])

In [33]:
C @ D @ C_inv

array([[ 8., 21.],
       [ 0., -1.]])

## 7

In [34]:
n = 5
D = np.array([
    [1**n, 0],
    [0, (-1)**n]
])
C = np.array([
    [1, 0],
    [1, 1]
])
C_inv = np.linalg.inv(C)
C_inv

array([[ 1.,  0.],
       [-1.,  1.]])

In [35]:
C @ D @ C_inv

array([[ 1.,  0.],
       [ 2., -1.]])