In [30]:
from sympy import *

import numpy as np
np.set_printoptions(suppress=True)

## 1

In [18]:
A = np.array([[4, -5, 6],
              [7, -8, 6],
              [3/2, -1/2, -2]])
vals, vecs = np.linalg.eig(A)
vecs

array([[-0.6882472 , -0.66666667,  0.40824829],
       [-0.6882472 , -0.66666667, -0.40824829],
       [-0.22941573,  0.33333333, -0.81649658]])

In [21]:
(2/6**(1/2))

0.8164965809277261

## 2

In [29]:
L = np.array([[0,0,0,1],
              [1,0,0,0],
              [0,1,0,0],
              [0,0,1,0]])
vals, vecs = np.linalg.eig(L)
print(vals)
vecs

[-1.+0.j  0.+1.j  0.-1.j  1.+0.j]


array([[-0.5+0.j ,  0. +0.5j,  0. -0.5j, -0.5+0.j ],
       [ 0.5+0.j ,  0.5-0.j ,  0.5+0.j , -0.5+0.j ],
       [-0.5+0.j ,  0. -0.5j,  0. +0.5j, -0.5+0.j ],
       [ 0.5+0.j , -0.5+0.j , -0.5-0.j , -0.5+0.j ]])

## 3

In [28]:
L_prime = np.array(
    [
        [0.1, 0.1, 0.1, 0.7],
        [0.7, 0.1, 0.1, 0.1],
        [0.1, 0.7, 0.1, 0.1],
        [0.1, 0.1, 0.7, 0.1],
    ]
)
vals, vecs = np.linalg.eig(L_prime)
print(vals)
vecs

[ 1. +0.j  -0.6+0.j  -0. +0.6j -0. -0.6j]


array([[ 0.5+0.j ,  0.5+0.j ,  0.5+0.j ,  0.5-0.j ],
       [ 0.5+0.j , -0.5+0.j ,  0. -0.5j,  0. +0.5j],
       [ 0.5+0.j ,  0.5+0.j , -0.5-0.j , -0.5+0.j ],
       [ 0.5+0.j , -0.5+0.j , -0. +0.5j, -0. -0.5j]])

## 4

In [27]:
L = np.array([[0,1,0,0],
              [1,0,0,0],
              [0,0,0,1],
              [0,0,1,0]])
vals, vecs = np.linalg.eig(L)
print(vals)
vecs

[ 1. -1.  1. -1.]


array([[ 0.70710678, -0.70710678,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        , -0.        ,  0.70710678, -0.70710678],
       [ 0.        , -0.        ,  0.70710678,  0.70710678]])

## 5

In [26]:

L_prime = np.array(
    [
        [0.1, 0.7, 0.1, 0.1],
        [0.7, 0.1, 0.1, 0.1],
        [0.1, 0.1, 0.1, 0.7],
        [0.1, 0.1, 0.7, 0.1],
    ]
)
vals, vecs = np.linalg.eig(L_prime)
print(vals)
vecs

[-0.6  0.6  1.  -0.6]


array([[ 0.70710678, -0.5       , -0.5       , -0.03736572],
       [-0.70710678, -0.5       , -0.5       ,  0.03736572],
       [ 0.        ,  0.5       , -0.5       , -0.70611883],
       [ 0.        ,  0.5       , -0.5       ,  0.70611883]])

## 6

In [31]:
l, a, b, c, d = symbols('l, a, b, c, d')

f = l**2 - (a + d)*l + (a*d - b*c)
f

a*d - b*c + l**2 - l*(a + d)

In [42]:
f_1 = f.subs({a: 3/2, b: -1, c: -1/2, d: 1/2})
f_1

l**2 - 2.0*l + 0.25

## 7

In [44]:
solveset(f_1)

{0.133974596215561, 1.86602540378444}

In [110]:
A = np.array([[3/2, -1],
              [-1/2, 1/2]])
vals, vecs = np.linalg.eig(A)
vals

array([1.8660254, 0.1339746])

In [111]:
3**(1/2)/2

0.8660254037844386

## 8

In Coursera's Jupyter:

```
[[ 2.732  1.   ]
 [-1.     1.366]]
```

In [112]:
vecs 

array([[ 0.9390708 ,  0.59069049],
       [-0.34372377,  0.80689822]])

In [113]:
0.93/-0.34

-2.735294117647059

In [114]:
0.59/0.80

0.7374999999999999

In [115]:
-1-3**(1/2)

-2.732050807568877

In [116]:
-1 + 3**(1/2)

0.7320508075688772

## 9

In [117]:
C = np.array([
    [-1-3**(1/2), -1 + 3**(1/2)],
    [1, 1]
])
C

array([[-2.73205081,  0.73205081],
       [ 1.        ,  1.        ]])

In [118]:
C_inv = np.linalg.inv(C)
C_inv

array([[-0.28867513,  0.21132487],
       [ 0.28867513,  0.78867513]])

In [119]:
C_inv @ A @ C

array([[ 1.8660254,  0.       ],
       [-0.       ,  0.1339746]])

In [120]:
1+3**(1/2)/2

-1.8660254037844386

In [122]:
1-3**(1/2)/2

0.1339745962155614

## 10

In [107]:
D = np.array([
    [(-1-3**(1/2)/2)**2, 0],
    [0, (-1+3**(1/2)/2)**2]
])
D

array([[3.48205081, 0.        ],
       [0.        , 0.01794919]])

In [108]:
C @ D @ C_inv

array([[ 2.75, -2.  ],
       [-1.  ,  0.75]])