In [52]:
import numpy as np

## 1

In [62]:
v = np.array([1, 2])
c = np.array([1, 1])

prod = (v*c).sum()
size_c = np.sqrt((c * c).sum())

c * (prod / size_c**2)

array([1.5, 1.5])

## 2

In [64]:
v = np.array([2, 1])
c = np.array([3, -4])

prod = (v*c).sum()
size_c = np.sqrt((c * c).sum())

v_c = c * (prod / size_c**2)

np.sqrt((v_c * v_c).sum())

0.4

## 3

In [67]:
def change_basis(v, bn):
    vn = []
    for b in bn:
        v_b = (v*b).sum() / (b*b).sum()
        #v_b = v_b if v_b.is_integer() else Fraction(str(v_b))
        vn.append(v_b)
    return np.array(vn)

In [69]:
v = np.array([-4, -3, 8])
b1 = np.array([1, 2, 3])
b2 = np.array([-2, 1, 0])
b3 = np.array([-3, -6, 5])

In [70]:
change_basis(v, [b1, b2, b3])

array([1., 1., 1.])

## 5

In [71]:
p = np.array([3, 2, 4])
v = np.array([-1, 2, -3])

p + (2*v)

array([ 1,  6, -2])