In [1]:
import numpy as np

## 5

In [11]:
A = np.array([
    [1, 0, -(4/13)/(-12/13)],
    [0, 1, -(-3/13)/(-12/13)]
])
A

array([[ 1.        ,  0.        ,  0.33333333],
       [ 0.        ,  1.        , -0.25      ]])

In [12]:
r = np.array([
    [6],
    [2],
    [3]
])
r

array([[6],
       [2],
       [3]])

In [13]:
A.dot(r)

array([[7.  ],
       [1.25]])

## 6

In [14]:
R = np.array([
    [5, -1, -3, 7],
    [4, -4, 1, -2],
    [9, 3, 0, 12],
])
R

array([[ 5, -1, -3,  7],
       [ 4, -4,  1, -2],
       [ 9,  3,  0, 12]])

In [15]:
np.set_printoptions(suppress=True)

A.dot(R)

array([[ 8.  , -0.  , -3.  , 11.  ],
       [ 1.75, -4.75,  1.  , -5.  ]])